-- +goose Up
ALTER TABLE rooms DROP PRIMARY KEY, MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (id);

-- +goose Down
ALTER TABLE rooms DROP PRIMARY KEY, MODIFY COLUMN id CHAR(36) NOT NULL DEFAULT (UUID()), ADD PRIMARY KEY (id);
