-- +goose Up
ALTER TABLE rooms DROP FOREIGN KEY rooms_ibfk_1;
ALTER TABLE users DROP PRIMARY KEY, MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (id);
ALTER TABLE rooms MODIFY COLUMN creator_id BIGINT NOT NULL;
ALTER TABLE rooms ADD CONSTRAINT rooms_ibfk_1 FOREIGN KEY (creator_id) REFERENCES users(id);

-- +goose Down
ALTER TABLE rooms DROP FOREIGN KEY rooms_ibfk_1;
ALTER TABLE rooms MODIFY COLUMN creator_id CHAR(36) NOT NULL;
ALTER TABLE users DROP PRIMARY KEY, MODIFY COLUMN id CHAR(36) NOT NULL DEFAULT (UUID()), ADD PRIMARY KEY (id);
ALTER TABLE rooms ADD CONSTRAINT rooms_ibfk_1 FOREIGN KEY (creator_id) REFERENCES users(id);
