import type { Metadata } from 'next';
import { Roboto_Condensed, Roboto_Mono } from 'next/font/google';
import './globals.css';
import { ClientProviders } from '@/providers/ClientProviders';
import { Toaster } from 'sonner'

const robotoCondensed = Roboto_Condensed({
  variable: '--font-roboto-condensed',
  subsets: ['latin'],
});

const robotoMono = Roboto_Mono({
  variable: '--font-roboto-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientProviders>
        <body
          className={`${robotoCondensed.variable} ${robotoMono.variable}
            antialiased`}
        >
          {children}
          <Toaster expand={true} visibleToasts={100}/>
        </body>
      </ClientProviders>
    </html>
  );
}
